name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # deploy setiap kali push ke branch main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Deploy to Firebase Hosting
        run: npx firebase-tools@latest deploy --only hosting --project component-life --json
        env:
          FIREBASE_SERVICE_ACCOUNT_COMPONENT_LIFE: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COMPONENT_LIFE }}
